[build]
  command = "npm install && npx expo export --platform web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/images/*"
  to = "http://8.137.33.157:3000/images/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://8.137.33.157:3000/api/:splat"
  status = 200
